import { ComidaDef } from './menu';
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class ComidasData {
  readonly comidas: ComidaDef[] = [
    // ─── CON CARNE ─────────────────────────────────────────────
    {
      id: 'cc-01',
      nombre: 'Pollo al horno con fideos (Pata muslo/Pechuga)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pata muslo o pechuga de pollo', cantidad: '5 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '4 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-02',
      nombre: 'Bife de pollo con fideos y ensalada de chaucha, papa y huevo',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bife de pollo (pechuga fileteada)', cantidad: '4 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Chauchas', cantidad: '1 kg' },
        { nombre: 'Papas', cantidad: '2 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-03',
      nombre: 'Salpicón de pollo (Pechuga, zanahoria, arvejas, tomate)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pechuga de pollo', cantidad: '3 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Arvejas (lata)', cantidad: '2 latas grandes' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Lechuga', cantidad: '2 unidades' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-04',
      nombre: 'Tarta de pollo y verduras (Pechuga, cebolla, pimiento, zanahoria, zapallito y acelga)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pechuga de pollo', cantidad: '2 kg' },
        { nombre: 'Tapas de tarta', cantidad: '6 tapas' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Zapallitos verdes', cantidad: '3 unidades' },
        { nombre: 'Acelga', cantidad: '2 atados' },
        { nombre: 'Huevo', cantidad: '6 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-05',
      nombre: 'Guiso de arroz (Pollo)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo o pechuga)', cantidad: '3 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento morrón', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '4 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-06',
      nombre: 'Guiso de arroz (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento morrón', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '4 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-07',
      nombre: 'Guiso de fideos (Pollo)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo o pechuga)', cantidad: '3 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-08',
      nombre: 'Guiso de fideos (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-09',
      nombre: 'Estofado de pollo con arroz (Pata muslo)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pata muslo de pollo', cantidad: '5 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-10',
      nombre: 'Pollo al horno con arroz',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo o pechuga)', cantidad: '5 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-11',
      nombre: 'Pollo salteado con verduras y arroz',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pechuga de pollo', cantidad: '3 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento morrón', cantidad: '1 unidad' },
        { nombre: 'Choclo en grano', cantidad: '1 lata' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-12',
      nombre: 'Empanadas (Pollo o Carne)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Tapas de empanada', cantidad: '60 tapas' },
        { nombre: 'Pollo o Carne molida', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '2 kg' },
        { nombre: 'Huevo duro', cantidad: '8 unidades' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Ají molido', cantidad: '1 cdita' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Grasa o aceite', cantidad: 'para pincelar' },
      ],
    },
    {
      id: 'cc-13',
      nombre: 'Sopa de pollo con verduras y fideos',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo o pechuga)', cantidad: '3 kg' },
        { nombre: 'Fideos sopa', cantidad: '500 g' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zapallo', cantidad: '1/2 kg' },
        { nombre: 'Papa', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'cc-14',
      nombre: 'Picante de pollo',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo)', cantidad: '5 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Ají molido', cantidad: '1 cdita' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Ajo', cantidad: '4 dientes' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-15',
      nombre: 'Pollo con puré',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pata muslo o pechuga)', cantidad: '5 kg' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-16',
      nombre: 'Milanesa con arroz (Blando o Bife)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda o bife', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-17',
      nombre: 'Milanesa con fideos (Blando o Bife)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda o bife', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Fideos', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-18',
      nombre: 'Milanesa con puré (Bife)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bife', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-19',
      nombre: 'Bife a la criolla con puré (Bifes)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bifes', cantidad: '3 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Tomate', cantidad: '1/2 kg' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-20',
      nombre: 'Bife encebollado con puré (Bifes)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bifes', cantidad: '3 kg' },
        { nombre: 'Cebolla', cantidad: '1.5 kg' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-21',
      nombre: 'Marinera con ensalada rusa (Bife)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bife', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Papas', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Arvejas', cantidad: '1 lata' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-22',
      nombre: 'Marineras con ensalada',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne para milanesa (bife o blando)', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Lechuga', cantidad: '2 unidades' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-23',
      nombre: 'Estofado de carne con fideos (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-24',
      nombre: 'Estofado de carne con papas (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Papas', cantidad: '3 kg' },
        { nombre: 'Zapallo', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-25',
      nombre: 'Guiso de lentejas (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Lentejas', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-26',
      nombre: 'Guiso de arroz con carne (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-27',
      nombre: 'Guiso de fideos con carne (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Fideos tirabuzón', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-28',
      nombre: 'Carne al horno con papas (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '3 kg' },
        { nombre: 'Papas', cantidad: '5 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-29',
      nombre: 'Carne salteada con verduras y arroz (Blando)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda (cuadrada o paleta)', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Zapallito', cantidad: '1/2 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-30',
      nombre: 'Milanesas a la napolitana con arroz (Bife, con queso)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Bife', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '1 kg' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'cc-31',
      nombre: 'Albóndigas en salsa con fideos (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Fideos', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-32',
      nombre: 'Albóndigas en salsa de tomate con fideos',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Fideos', cantidad: '2 kg' },
        { nombre: 'Puré de tomate', cantidad: '700 cc' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-33',
      nombre: 'Albóndigas con puré (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-34',
      nombre: 'Fideos con salsa boloñesa (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Fideos', cantidad: '2.5 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '700 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-35',
      nombre: 'Arroz con salsa de carne (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-36',
      nombre: 'Pastel de papa (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Papas', cantidad: '5 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-37',
      nombre: 'Pan de carne (Molida, huevo, zanahoria, pimiento, cebolla y berenjena) con puré de papa y zapallo',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Huevo', cantidad: '6 unidades' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Berenjenas', cantidad: '3 unidades' },
        { nombre: 'Papas', cantidad: '3 kg' },
        { nombre: 'Zapallo', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-38',
      nombre: 'Hamburguesa de carne con arroz',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para cocinar' },
      ],
    },
    {
      id: 'cc-39',
      nombre: 'Hamburguesas con papas o batatas (Molida)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '3 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Papas', cantidad: '3 kg' },
        { nombre: 'Batatas', cantidad: '2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para cocinar' },
      ],
    },
    {
      id: 'cc-40',
      nombre: 'Zapallitos rellenos con carne (con queso)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Zapallitos verdes', cantidad: '13 unidades' },
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Arroz', cantidad: '1 kg' },
        { nombre: 'Queso cremoso', cantidad: '300 g' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-41',
      nombre: 'Pastel de polenta (con queso)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Polenta', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Queso cremoso', cantidad: '300 g' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-42',
      nombre: 'Canelones de pollo (cebolla, pimiento, zanahoria, zapallito)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Pollo (pechuga)', cantidad: '3 kg' },
        { nombre: 'Tapas de canelones', cantidad: '50 tapas' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Zapallito', cantidad: '3 unidades' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-43',
      nombre: 'Ñoquis con salsa de carne',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne molida', cantidad: '2 kg' },
        { nombre: 'Ñoquis', cantidad: '4 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-44',
      nombre: 'Puchero a la olla con puré (Osobuco)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Osobuco', cantidad: '3 kg' },
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zapallo', cantidad: '1 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'cc-45',
      nombre: 'Puchero completo con verduras (Osobuco)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Osobuco', cantidad: '3 kg' },
        { nombre: 'Papas', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Zapallo', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Arroz', cantidad: '500 g' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'cc-46',
      nombre: 'Sopa completa con carne y verduras',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne (blando o osobuco)', cantidad: '2 kg' },
        { nombre: 'Papa', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Zapallo', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Fideos sopa', cantidad: '500 g' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'cc-47',
      nombre: 'Polenta con salsa (Blando o Bifes)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Carne blanda o bifes', cantidad: '2 kg' },
        { nombre: 'Polenta', cantidad: '2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'cc-48',
      nombre: 'Sopa con puchero (fideos)',
      conCarne: true,
      ingredientes: [
        { nombre: 'Osobuco o carne blando', cantidad: '2 kg' },
        { nombre: 'Fideos sopa', cantidad: '500 g' },
        { nombre: 'Papa', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Zapallo', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },

    // ─── SIN CARNE ─────────────────────────────────────────────
    {
      id: 'sc-01',
      nombre: 'Papa con queso / Bombita de papa con ensalada (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Papas', cantidad: '5 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Lechuga', cantidad: '2 unidades' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír las bombas' },
      ],
    },
    {
      id: 'sc-02',
      nombre: 'Tarta de verduras (cebolla, pimiento, zanahoria, zapallito y acelga, con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Tapas de tarta', cantidad: '6 tapas' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Zapallitos verdes', cantidad: '3 unidades' },
        { nombre: 'Acelga', cantidad: '3 atados' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Huevo', cantidad: '6 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'sc-03',
      nombre: 'Tarta de choclo y queso',
      conCarne: false,
      ingredientes: [
        { nombre: 'Tapas de tarta', cantidad: '6 tapas' },
        { nombre: 'Choclo en grano (lata)', cantidad: '4 latas' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Huevo', cantidad: '6 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'sc-04',
      nombre: 'Pizza (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Harina', cantidad: '2 kg' },
        { nombre: 'Levadura', cantidad: '50 g' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Queso cremoso', cantidad: '1 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-05',
      nombre: 'Arroz con salsa',
      conCarne: false,
      ingredientes: [
        { nombre: 'Arroz', cantidad: '2.5 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-06',
      nombre: 'Milanesa de berenjena a la napolitana con batatas, calabazas y zanahorias al horno',
      conCarne: false,
      ingredientes: [
        { nombre: 'Berenjenas grandes', cantidad: '8 unidades' },
        { nombre: 'Pan rallado', cantidad: '500 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Batatas', cantidad: '3 kg' },
        { nombre: 'Zapallo anco/calabaza', cantidad: '2 kg' },
        { nombre: 'Zanahoria', cantidad: '1 kg' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'sc-07',
      nombre: 'Bocaditos de verduras con papa hervida, choclo y zapallo (cebolla, acelga, zanahoria, zapallito y pimiento)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Acelga', cantidad: '2 atados' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Zapallitos verdes', cantidad: '4 unidades' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Papas', cantidad: '3 kg' },
        { nombre: 'Choclo', cantidad: '13 unidades' },
        { nombre: 'Zapallo', cantidad: '2 kg' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: 'para freír' },
      ],
    },
    {
      id: 'sc-08',
      nombre: 'Polenta con salsa de tomate y queso',
      conCarne: false,
      ingredientes: [
        { nombre: 'Polenta', cantidad: '2 kg' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Queso cremoso', cantidad: '400 g' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-09',
      nombre: 'Hamburguesas de lentejas (cebolla, zanahoria y pimiento salteados) con arroz (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Lentejas', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Queso cremoso', cantidad: '400 g' },
        { nombre: 'Ajo', cantidad: '2 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-10',
      nombre: 'Sopa paraguaya (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Harina de maíz', cantidad: '1 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Queso cremoso', cantidad: '700 g' },
        { nombre: 'Huevo', cantidad: '8 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-11',
      nombre: 'Tortilla de papas con ensalada de tomate, cebolla, lentejas y zanahoria',
      conCarne: false,
      ingredientes: [
        { nombre: 'Papas', cantidad: '4 kg' },
        { nombre: 'Huevo', cantidad: '12 unidades' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Tomate', cantidad: '1 kg' },
        { nombre: 'Lentejas cocidas', cantidad: '1/2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-12',
      nombre: 'Pastel de verduras (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Papas', cantidad: '3 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Berenjenas', cantidad: '2 unidades' },
        { nombre: 'Zapallitos verdes', cantidad: '3 unidades' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-13',
      nombre: 'Fideos salteados con verduras',
      conCarne: false,
      ingredientes: [
        { nombre: 'Fideos tirabuzón', cantidad: '2.5 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento morrón', cantidad: '1 unidad' },
        { nombre: 'Zapallito', cantidad: '2 unidades' },
        { nombre: 'Berenjena', cantidad: '2 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-14',
      nombre: 'Sopa de zapallo',
      conCarne: false,
      ingredientes: [
        { nombre: 'Zapallo', cantidad: '3 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Papa', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Sal', cantidad: 'a gusto' },
      ],
    },
    {
      id: 'sc-15',
      nombre: 'Canelones de verdura (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Tapas de canelones', cantidad: '50 tapas' },
        { nombre: 'Acelga', cantidad: '3 atados' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zapallo', cantidad: '1/2 kg' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-16',
      nombre: 'Ñoquis con salsa',
      conCarne: false,
      ingredientes: [
        { nombre: 'Ñoquis', cantidad: '4 kg' },
        { nombre: 'Puré de tomate', cantidad: '700 cc' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-17',
      nombre: 'Arroz con verduras salteadas',
      conCarne: false,
      ingredientes: [
        { nombre: 'Arroz', cantidad: '2.5 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Zapallito', cantidad: '2 unidades' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-18',
      nombre: 'Arroz con salsa y queso',
      conCarne: false,
      ingredientes: [
        { nombre: 'Arroz', cantidad: '2.5 kg' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Queso cremoso', cantidad: '400 g' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Orégano', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-19',
      nombre: 'Papas rellenas (con queso)',
      conCarne: false,
      ingredientes: [
        { nombre: 'Papas grandes', cantidad: '13 unidades' },
        { nombre: 'Queso cremoso', cantidad: '500 g' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Pimienta', cantidad: 'a gusto' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-20',
      nombre: 'Albóndigas de lentejas en salsa con arroz',
      conCarne: false,
      ingredientes: [
        { nombre: 'Lentejas', cantidad: '1 kg' },
        { nombre: 'Pan rallado', cantidad: '300 g' },
        { nombre: 'Huevo', cantidad: '4 unidades' },
        { nombre: 'Cebolla', cantidad: '1/2 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Arroz', cantidad: '2 kg' },
        { nombre: 'Puré de tomate', cantidad: '500 cc' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
    {
      id: 'sc-21',
      nombre: 'Guiso de lentejas',
      conCarne: false,
      ingredientes: [
        { nombre: 'Lentejas', cantidad: '1 kg' },
        { nombre: 'Zanahoria', cantidad: '1/2 kg' },
        { nombre: 'Cebolla', cantidad: '1 kg' },
        { nombre: 'Pimiento', cantidad: '1 unidad' },
        { nombre: 'Puré de tomate', cantidad: '300 cc' },
        { nombre: 'Ajo', cantidad: '3 dientes' },
        { nombre: 'Sal', cantidad: 'a gusto' },
        { nombre: 'Comino', cantidad: '1 cdita' },
        { nombre: 'Aceite', cantidad: '1/4 taza' },
      ],
    },
  ];

  getComidasConCarne(): ComidaDef[] {
    return this.comidas.filter(c => c.conCarne);
  }

  getComidasSinCarne(): ComidaDef[] {
    return this.comidas.filter(c => !c.conCarne);
  }

  getComidaById(id: string): ComidaDef | undefined {
    return this.comidas.find(c => c.id === id);
  }
}
